-- Expand the legacy interaction tables before switching public DTOs.
-- Apply once per environment; do not edit this file after it is recorded.
ALTER TABLE comments ADD COLUMN status TEXT NOT NULL DEFAULT 'approved';
ALTER TABLE comments ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE comments ADD COLUMN deleted_at TEXT;
CREATE INDEX IF NOT EXISTS idx_comments_public ON comments(post_id, status, deleted_at, created_at DESC);

ALTER TABLE likes ADD COLUMN actor_hash TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_likes_post_actor_hash ON likes(post_id, actor_hash);

CREATE TABLE IF NOT EXISTS schema_migrations (
  migration_id TEXT PRIMARY KEY,
  checksum TEXT NOT NULL,
  applied_at TEXT NOT NULL,
  applied_by TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS interaction_mutations (
  site_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  mutation_id TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  response_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now', '+8 hours')),
  PRIMARY KEY (site_id, kind, mutation_id)
);
CREATE INDEX IF NOT EXISTS idx_interaction_mutations_created_at ON interaction_mutations(created_at);
